### ISSUE TITLE
학습된 모델에 대해서

### ISSUE THREAD

**Issue by khm159** [sangtaik/STT#2]
안녕하십니까. 
먼저, 좋은 코드를 공유해주셔서 감사드립니다.
현재 이 코드를 기반으로 한국어음성인식을 공부하고있습니다만, 
혹시 학습된 모델 파일의 공유가 가능할지 여쭙습니다.

감사합니다.

**Comment by sangtaik** [comment]
안녕하세요. 훈련을 마친 모델 파일은 현재 제가 가지고 있는게 없습니다.
onnx 모델의 경우 https://github.com/Mu-jun/STT 에 있는 파일로 훈련하셔야 합니다.

**Comment by khm159** [comment]
알겠습니다. 감사합니다!
